#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1573469723                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Keep track of your cashflow and budget

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Nineone Software Inc.                                
your_link                                 :                      
your_city                                 : Vancouver                                
email_address                             : nineonesoftware@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Insight
    description                           : Easily track the flow of cash between accounts visually. See what each account's balances will be on certain days of the calendar.
    fontawesome_icon_name                 : sync

  - title                                 : Data at a Glance
    description                           : With an innovative calendar display you can easily view all of your transactions and cashflow balances at a glance.
    fontawesome_icon_name                 : adjust

  - title                                 : History
    description                           : It feels good to have all of your data in one place. View a transaction's details that happened yesterday... or last year.
    fontawesome_icon_name                 : magic
  
  - title                                 : Budget
    description                           : Organize your transaction data by category to see what your top spending categories are.
    fontawesome_icon_name                 : star

  - title                                 : Shared Accounts
    description                           : Connect your account with a friend or family member to view and update transactions on a shared account together.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Unlimited
    description                           : Add an unlimited amount of accounts, transactions as well as shared accounts.
    fontawesome_icon_name                 : infinity


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/moneybg.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#ffffff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6C63FF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"






####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown